version: "3.9"
services:
    web:
        build: nginx
        ports:
          - 80:80
          - 443:443
        depends_on:
          - nlpapi

    nlpapi:
        build: nlpapi
        environment:
          - PORT=5000
        ports:
          - 5000:5000
